// Données statiques centralisées pour l'application

import { Clinic } from "@/types/clinic";
import { Service } from "@/types/service";
import { Appointment } from "@/types/appointment";

export const staticClinics: Clinic[] = [
  {
    id: "1",
    name: "Clinique Centrale",
    address: "123 Rue de la Paix, Tunis",
    city: "Tunis",
    phone: "+216 71 123 456",
    email: "contact@clinique-centrale.tn",
    description: "Clinique générale avec tous les services",
    servicesCount: 8,
  },
  {
    id: "2",
    name: "Clinique de l'Espoir",
    address: "456 Avenue Mohamed V, Sfax",
    city: "Sfax",
    phone: "+216 74 234 567",
    email: "info@esperance.tn",
    description: "Spécialisée en chirurgie et dentologie",
    servicesCount: 5,
  },
  {
    id: "3",
    name: "Centre Médical Moderne",
    address: "789 Rue Bourguiba, Sousse",
    city: "Sousse",
    phone: "+216 73 345 678",
    email: "hello@centre-moderne.tn",
    description: "Équipements modernes et staff expérimenté",
    servicesCount: 6,
  },
  {
    id: "4",
    name: "Polyclinique Santé Plus",
    address: "321 Boulevard Azaiez, Kairouan",
    city: "Kairouan",
    phone: "+216 77 456 789",
    email: "contact@santeplus.tn",
    description: "Radiologie et laboratoire avancés",
    servicesCount: 7,
  },
];

export const staticServices: Service[] = [
  {
    id: "1",
    name: "Consultation Générale",
    description: "Visite médicale complète",
    clinicName: "Clinique Centrale",
    clinicId: "1",
    price: 50000,
    duration: 30,
    isActive: true,
  },
  {
    id: "2",
    name: "Détartrage Dentaire",
    description: "Nettoyage et détartrage complet",
    clinicName: "Clinique Centrale",
    clinicId: "1",
    price: 75000,
    duration: 45,
    isActive: true,
  },
  {
    id: "3",
    name: "Radiologie",
    description: "Radiographies numériques",
    clinicName: "Clinique de l'Espoir",
    clinicId: "2",
    price: 35000,
    duration: 15,
    isActive: true,
  },
  {
    id: "4",
    name: "Chirurgie Mineure",
    description: "Interventions chirurgicales légères",
    clinicName: "Clinique de l'Espoir",
    clinicId: "2",
    price: 150000,
    duration: 90,
    isActive: true,
  },
  {
    id: "5",
    name: "Analyse Sanguin",
    description: "Tests sanguins complets",
    clinicName: "Clinique Centrale",
    clinicId: "1",
    price: 45000,
    duration: 20,
    isActive: true,
  },
];

export const staticAppointments: Appointment[] = [
  {
    id: "1",
    patientName: "Ahmed Ben Ali",
    serviceName: "Consultation Générale",
    clinicName: "Clinique Centrale",
    appointmentDate: "2024-02-15",
    appointmentTime: "09:30",
    status: "confirmed",
    notes: "Visite de suivi",
  },
  {
    id: "2",
    patientName: "Fatima Chaouech",
    serviceName: "Détartrage Dentaire",
    clinicName: "Clinique Centrale",
    appointmentDate: "2024-02-16",
    appointmentTime: "14:00",
    status: "pending",
    notes: "Nettoyage complet",
  },
  {
    id: "3",
    patientName: "Mohamed Khaled",
    serviceName: "Radiologie",
    clinicName: "Clinique de l'Espoir",
    appointmentDate: "2024-02-17",
    appointmentTime: "11:00",
    status: "confirmed",
    notes: "Radiographie thoracique",
  },
  {
    id: "4",
    patientName: "Leila Sami",
    serviceName: "Analyse Sanguin",
    clinicName: "Clinique Centrale",
    appointmentDate: "2024-02-18",
    appointmentTime: "08:00",
    status: "completed",
    notes: "Bilan complet sanguin",
  },
  {
    id: "5",
    patientName: "Ali Mahmoud",
    serviceName: "Chirurgie Mineure",
    clinicName: "Clinique de l'Espoir",
    appointmentDate: "2024-02-19",
    appointmentTime: "15:30",
    status: "cancelled",
    notes: "Intervention reportée",
  },
];
